In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
file1 = pd.read_csv('https://raw.githubusercontent.com/AshishJangra27/Machine-Learning-with-Python-GFG/main/Insurance/insurance.csv')

In [3]:
file1.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
file1['male'] = pd.get_dummies(file1['sex'], drop_first=True).astype('int')

In [5]:
file1

      age     sex     bmi  children smoker     region      charges  male
0      19  female  27.900         0    yes  southwest  16884.92400     0
1      18    male  33.770         1     no  southeast   1725.55230     1
2      28    male  33.000         3     no  southeast   4449.46200     1
3      33    male  22.705         0     no  northwest  21984.47061     1
4      32    male  28.880         0     no  northwest   3866.85520     1
...   ...     ...     ...       ...    ...        ...          ...   ...
1333   50    male  30.970         3     no  northwest  10600.54830     1
1334   18  female  31.920         0     no  northeast   2205.98080     0
1335   18  female  36.850         0     no  southeast   1629.83350     0
1336   21  female  25.800         0     no  southwest   2007.94500     0
1337   61  female  29.070         0    yes  northwest  29141.36030     0

[1338 rows x 8 columns]

In [6]:
file1['smoker'] = pd.get_dummies(file1['smoker'], drop_first = True).astype('int')

In [7]:
file1

      age     sex     bmi  children  smoker     region      charges  male
0      19  female  27.900         0       1  southwest  16884.92400     0
1      18    male  33.770         1       0  southeast   1725.55230     1
2      28    male  33.000         3       0  southeast   4449.46200     1
3      33    male  22.705         0       0  northwest  21984.47061     1
4      32    male  28.880         0       0  northwest   3866.85520     1
...   ...     ...     ...       ...     ...        ...          ...   ...
1333   50    male  30.970         3       0  northwest  10600.54830     1
1334   18  female  31.920         0       0  northeast   2205.98080     0
1335   18  female  36.850         0       0  southeast   1629.83350     0
1336   21  female  25.800         0       0  southwest   2007.94500     0
1337   61  female  29.070         0       1  northwest  29141.36030     0

[1338 rows x 8 columns]

In [8]:
Region = pd.get_dummies(file1['region']).astype('int')

In [9]:
Region

      northeast  northwest  southeast  southwest
0             0          0          0          1
1             0          0          1          0
2             0          0          1          0
3             0          1          0          0
4             0          1          0          0
...         ...        ...        ...        ...
1333          0          1          0          0
1334          1          0          0          0
1335          0          0          1          0
1336          0          0          0          1
1337          0          1          0          0

[1338 rows x 4 columns]

In [10]:
file1 = pd.concat([file1, Region], axis = 1)

In [11]:
file1

,age,sex,bmi,children,smoker,region,charges,male,northeast,northwest,southeast,southwest
0,19,female,27.900,0,1,southwest,16884.92400,0,0,0,0,1
1,18,male,33.770,1,0,southeast,1725.55230,1,0,0,1,0
2,28,male,33.000,3,0,southeast,4449.46200,1,0,0,1,0
3,33,male,22.705,0,0,northwest,21984.47061,1,0,1,0,0
4,32,male,28.880,0,0,northwest,3866.85520,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,0,northwest,10600.54830,1,0,1,0,0
1334,18,female,31.920,0,0,northeast,2205.98080,0,1,0,0,0
1335,18,female,36.850,0,0,southeast,1629.83350,0,0,0,1,0
1336,21,female,25.800,0,0,southwest,2007.94500,0,0,0,0,1
1337,61,female,29.070,0,1,northwest,29141.36030,0,0,1,0,0

In [12]:
import statsmodels.api as sm

In [13]:
X = file1.drop(['sex', 'region', 'charges', 'northeast', 'northwest', 'southeast', 'southwest'], axis = 1)

In [14]:
X

      age     bmi  children  smoker  male
0      19  27.900         0       1     0
1      18  33.770         1       0     1
2      28  33.000         3       0     1
3      33  22.705         0       0     1
4      32  28.880         0       0     1
...   ...     ...       ...     ...   ...
1333   50  30.970         3       0     1
1334   18  31.920         0       0     0
1335   18  36.850         0       0     0
1336   21  25.800         0       0     0
1337   61  29.070         0       1     0

[1338 rows x 5 columns]

In [15]:
y = file1['charges']

In [16]:
X_constant = sm.add_constant(X)

In [17]:
model = sm.OLS(y, X_constant)

In [18]:
result = model.fit()

In [19]:
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                charges   R-squared:                       0.750
Model:                            OLS   Adj. R-squared:                  0.749
Method:                 Least Squares   F-statistic:                     798.0
Date:                Fri, 19 Apr 2024   Prob (F-statistic):               0.00
Time:                        09:25:24   Log-Likelihood:                -13551.
No. Observations:                1338   AIC:                         2.711e+04
Df Residuals:                    1332   BIC:                         2.715e+04
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.205e+04    951.260    -12.670      0.000   -1.39e+04   -1.02e+04
age          257.7350     11.904     21.651      0.000     234.383     281.087
bmi          322.3642     27.419     11.757      0.000     268.576     376.153
children     474.4111    137.856      3.441      0.001     203.973     744.849
smoker      2.382e+04    412.523     57.750      0.000     2.3e+04    2.46e+04
male        -128.6399    333.361     -0.386      0.700    -782.609     525.329
==============================================================================
Omnibus:                      301.103   Durbin-Watson:                   2.087
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              720.380
Skew:                           1.214   Prob(JB):                    3.73e-157
Kurtosis:                       5.650   Cond. No.                         295.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [20]:
X.drop('male', inplace = True, axis = 1)

In [21]:
X

      age     bmi  children  smoker
0      19  27.900         0       1
1      18  33.770         1       0
2      28  33.000         3       0
3      33  22.705         0       0
4      32  28.880         0       0
...   ...     ...       ...     ...
1333   50  30.970         3       0
1334   18  31.920         0       0
1335   18  36.850         0       0
1336   21  25.800         0       0
1337   61  29.070         0       1

[1338 rows x 4 columns]

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
scaler = StandardScaler()

In [24]:
X['age'] = scaler.fit_transform(X['age'].values.reshape(-1, 1))
X['bmi'] = scaler.fit_transform(X['bmi'].values.reshape(-1, 1))

In [25]:
X

           age       bmi  children  smoker
0    -1.438764 -0.453320         0       1
1    -1.509965  0.509621         1       0
2    -0.797954  0.383307         3       0
3    -0.441948 -1.305531         0       0
4    -0.513149 -0.292556         0       0
...        ...       ...       ...     ...
1333  0.768473  0.050297         3       0
1334 -1.509965  0.206139         0       0
1335 -1.509965  1.014878         0       0
1336 -1.296362 -0.797813         0       0
1337  1.551686 -0.261388         0       1

[1338 rows x 4 columns]

In [26]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [27]:
from sklearn.svm import SVR


regressor = SVR(kernel = 'rbf', C = 10000, gamma = 0.1)

In [28]:
y_train

25      14001.13380
336     12142.57860
47       3556.92230
106      2331.51900
1269     8615.30000
           ...
1095     4561.18850
1130     8582.30230
1294    11931.12525
860     46113.51100
1126    10214.63600
Name: charges, Length: 802, dtype: float64

In [29]:
regressor.fit(X_train, y_train)

SVR(C=10000, gamma=0.1)

In [30]:
predict = regressor.predict(X_test)

In [31]:
predict

array([ 8528.58896924,  4912.66803752, 29743.35919625,  9437.50222273,
       28028.48599303,  4800.73056392,  1706.55372399, 14273.63189643,
        3343.64315788, 10494.81067703, 19291.08036489,  7341.2969223 ,
        3952.06724091, 41304.61357421, 43206.58608491, 46257.42781814,
        9883.03336258, 45060.07039682,  8245.02010215, 25938.59411446,
        6012.00087415,  7946.56189771,  1864.27841848,  2316.9661239 ,
       10832.99555812, 10411.8440029 , 12744.12766927,  4713.89056181,
        9158.68073244,  1736.33908805,  8254.00381717, 11551.09614486,
        2179.97526069,  5578.33979593,  3407.3067836 ,  7356.27103195,
        2530.43003092,  7325.9387451 , 24829.2987368 , 40847.51686881,
        4966.68369216,  2786.79345459, 11987.63369216, 12311.64533122,
        5386.27521399, 13030.98711602,  3467.40856964,  4358.56592529,
       38682.01457001,  4998.56393345, 13921.71507936,  2199.75036283,
        6334.16231141,  1631.53515563, 11180.52637831, 10296.73128374,
        3564.37426959, 33078.32561267, 11950.20796656, 10046.31818683,
       13944.75685033,  4877.98697193, 15222.4154313 ,  7644.14842281,
        9665.50487314,  3727.93026889, 16240.1223653 , 11490.72257025,
        3163.15732569,  2316.00159762,  5891.51162831,  8899.77579064,
        8302.78417337,  6801.70334959,  7598.66682653,  4911.95995585,
        4779.3256383 , 11147.21798223,  4425.65268176,  9118.93190259,
        2038.92154109, 29150.82686795,  5143.36590796, 36294.00298638,
       28251.61077694, 35582.41351256,  5266.89765094, 10788.66480395,
        7927.84712198, 12104.89766628, 15134.00574426, 24386.19004377,
       27259.51226452,  4931.50214486, 40562.09278382,  7352.72243502,
       29122.32017004,  2035.22969044, 18363.53106894,  5877.93454179,
        4140.49007017,  1828.63361768,  6178.65994313, 13268.79301221,
       13087.74550804,  2338.24390774,  8234.67272031, 19086.26169291,
        1592.09629905, 23035.30810302,  1911.91694703,  3422.9159034 ,
       12769.81194212, 35185.53663542,  9271.66332333,  2538.98127756,
       12720.42425205, 27574.17095765,  6280.0735606 ,  2863.06946982,
        4980.40203959,  7366.56682398, 11103.14779384,  2605.27142016,
        4383.73316732,  7359.07695967,  7318.73475959,  9261.11517135,
       12349.11432522,  2463.51273048,  4018.36106989,  6376.92414333,
        5823.9509514 ,  7362.88998371,  5662.14886896, 13208.20460849,
        4251.24637252, 31254.46359121, 42479.42825514, 31600.65943914,
        4888.50388942,  9331.85688037,  2924.009864  , 11113.07070592,
        2646.15574196, 27075.17742463,  5351.2019275 ,  3815.24631227,
       11353.98228184,  5220.93244055, 41608.07797242,  2373.92559577,
        1898.16229419, 37360.32710595,  5814.56469259,  4470.73210264,
       13542.25062445,  8577.62773411, 29566.66162138, 38281.43671875,
       13430.17738441,  2225.7341809 , 15427.39201863,  2297.60368054,
        4244.14639007,  7668.54505201, 42257.83227842, 35349.04307384,
       36667.7290601 ,  2733.74273879,  9252.37306472,  6203.66059449,
        5621.15678807,  4331.95163235,  2198.64916095, 25932.12861247,
       21872.93991786, 14155.18526912, 13074.36061085, 11534.91942802,
       30855.70036983,  2837.50843972,  8651.78036081,  4976.15058329,
        5151.78937212,  2604.09964325,  3952.37941803,  3596.68908259,
        8366.45696159, 10764.50919671,  4463.54192775,  1711.93224885,
        2127.96574067, 39429.965741  , 13468.46588585,  9333.27131106,
        2202.25000823, 11705.46650334,  1636.24469494,  8959.50715477,
        2783.66407016, 28448.78164492,  4912.2768558 ,  2999.88299026,
       22023.35962639, 19227.78408145,  8954.95857424,  4078.68216721,
        8313.28952808,  3200.49333282, 13441.47088217, 12126.74811414,
        8779.80689394, 22687.50507076,  7090.67752507,  3600.09297531,
        4768.82075851, 14161.41896442, 12701.43609309,  5198.37401141,
        2182.77109605,  7052.85724771,  7247.8291814 , 44876.90380186,
        2296.36406214, 30761.92828602,  1735.44327441,  1868.38702028,
        9977.98962189, 10779.68493723,  2184.6839256 ,  9432.50399523,
        4558.90581996, 27550.53125444,  9766.3541799 ,  8657.04808346,
        4063.98496119,  6473.22645224, 45560.26965529,  2310.89437669,
       12625.85056474, 37777.0141355 ,  2763.53579646,  3406.44724312,
        1735.73262011,  2910.51099797,  4355.87494648,  4557.37753299,
       11169.43747323,  1931.81421011,  1975.72705282,  7690.22994847,
        3181.88986406, 11536.25027422,  2391.56299732,  3256.99910638,
       12721.92965556,  3421.24909027,  8653.74963644,  5439.82692962,
        7615.66033118, 13053.09864529, 26399.72172525, 40394.68705315,
       11922.18933303,  5951.55212263, 39157.63564092, 10029.88126771,
        8982.74377898,  7969.36924288,  9668.4446492 ,  8283.261272  ,
       12019.58504901, 13719.92428778,  2140.42048862, 13402.0137555 ,
        6338.79008215, 39753.63542422,  5691.42211696,  9658.92771366,
        8614.19126931, 14216.49915755, 10901.87089514,  8969.38941663,
       37532.2049165 ,  2655.63078864, 10021.52890386, 47229.65813856,
        4135.30477857,  2761.06536147,  1774.60090286, 11533.23781052,
       12463.66957852, 10722.98371476, 10642.99473191, 10402.90654451,
        9991.22155863,  3426.51972186,  2221.15947024, 36946.03818529,
       30952.83987391,  6825.04316253,  3131.33808144, 20458.43069701,
       13735.48485286, 36500.44679646,  1996.9193494 , 39148.35121297,
        5617.30817272,  1850.2750828 ,  6303.69498948,  2220.32626406,
       17908.9637639 , 13544.28899923,  2493.16043296, 12406.70998455,
       10790.29680917, 11954.3803405 , 38775.71868219, 12674.94206966,
       22815.15358841,  7946.39441555, 15734.2077898 ,  4151.85495743,
        8243.89148342,  8529.00075227, 14831.79102563, 11331.3975126 ,
        2739.15003122, 11155.36904832, 12715.53664665, 11956.7011637 ,
        4983.98970874, 25677.78397296,  6194.18665033,  2447.04248073,
        4352.86394592,  9980.96103434, 44475.47960098,  8851.65966918,
       13907.48580864,  6807.28729319,  4836.06393963,  4333.15871104,
        1735.73942609,  7928.36604947,  5951.37495646,  1763.35922666,
       11488.38818814,  7633.75290491,  5574.76774468,  2955.63105303,
        9925.80623281,  2606.30174787, 34206.03783797, 33543.02763389,
       42712.57874066,  3273.80514911,  8241.9197573 ,  6182.55348895,
        2038.60081102, 24780.50093348,  6773.92283362, 15812.58895157,
       44035.98020561,  5456.91056602, 12730.33995841,  5602.81067244,
        9237.16774305,  9958.06777373, 17163.87899988, 12053.00785772,
        6202.86800263,  4122.58107128,  2767.81964528, 11148.0873812 ,
       29665.6640755 , 11555.2870428 , 10350.29412456,  2893.89290692,
        3174.20901956,  6443.41910966,  8315.93690194,  9505.38911517,
       26165.24926383, 42865.9809124 , 11927.75173866,  7022.96923384,
       13094.42515813, 10471.71947756,  6550.83019841,  3988.40670766,
        7074.20778882,  4021.54846024,  8615.92442612,  4551.72111167,
       11919.71953667,  8903.89564097,  4910.36544571,  1686.68093629,
       11955.96503358,  2345.21711767, 13135.44336533,  7633.78987906,
       12443.72318524, 34402.96339915, 37321.47659676, 40922.94614064,
        4557.06054287,  3423.19334539, 12701.46955548,  6549.20223001,
       39773.12151858,  2316.65982757,  6527.66608584, 12066.87593496,
       21947.16894356,  4963.46579797,  2683.14950891, 11495.43578595,
        3830.67768843,  4557.9078652 ,  6463.64308694,  1732.50313178,
       20579.12908376,  8554.29345834,  6040.20711428,  3273.38603849,
        5372.56132647, 12721.48617325, 25925.06467699,  8225.77297097,
        7359.9225678 ,  3834.72912062,  6544.2270318 ,  2440.95580236,
        5949.55989594,  7967.92722218, 11148.0405967 , 10615.57788318,
        5007.67094231,  2447.08483764,  6734.42840399, 41098.15600513,
       35278.21761795,  1909.20365694, 43200.40626349, 33561.34481601,
       11424.1590106 ,  1935.02216359, 13426.05815157,  1923.65011143,
        8954.15426907, 33399.89236012, 16014.04436956, 10913.94022604,
        6475.70165165, 12322.52220509,  3514.12961381,  8914.23064765,
        4184.87395679, 12127.46233191,  9617.62918042,  6718.61361493,
        3475.69810863,  4027.01937409,  8521.80945719,  5948.98556341,
       22271.88762529, 12262.70702003,  1978.77524997, 31724.86826914,
       30027.39884133,  2888.13834439,  1960.97095558, 14158.05277182,
        4485.93508223, 12380.34177252, 12129.95663662,  3770.8795834 ,
        6185.58579231,  9542.58524268,  2184.69587122,  2555.14416195,
        4353.15798043,  1942.89135952,  2737.89943138, 29483.18063883,
        7059.85707326, 28713.75376825, 26906.47225083, 12851.43693319,
       11831.54853288,  4582.72520124, 10740.12356186,  7666.80856001,
       11035.01404716, 14675.42398687, 10026.72040934,  6480.2042482 ,
        9327.17354139,  8232.73245913,  2457.03642652, 10796.16383113,
        4205.17752402,  8908.41542325, 14462.90241972,  1616.03988237,
       10022.05419959, 19817.09717893, 12700.24604485, 47613.87789177,
       40849.09688371,  8221.53463928,  5463.21765404, 31816.11931036,
        1765.6346964 , 33943.91225224,  9586.45468773,  2612.76357728,
       13706.0844876 ,  4952.27117564,  8272.71809762,  1726.58979569,
        4776.68463509,  5450.07497999,  7374.91688892,  2704.23367974,
       12241.63601231,  7340.08910161, 22621.42615587, 13135.59765109,
        6447.96219137,  5388.0229824 ,  9819.7602513 , 38730.45016553])

In [32]:
y = y_test.iloc[:].values

In [33]:
y

array([ 9095.06825 ,  5272.1758  , 29330.98315 ,  9301.89355 ,
       33750.2918  ,  4536.259   ,  2117.33885 , 14210.53595 ,
        3732.6251  , 10264.4421  , 18259.216   ,  7256.7231  ,
        3947.4131  , 46151.1245  , 48673.5588  , 44202.6536  ,
        9800.8882  , 42969.8527  ,  8233.0975  , 21774.32215 ,
        5080.096   ,  7441.501   ,  1256.299   ,  2755.02095 ,
       11085.5868  , 10923.9332  , 12644.589   , 18804.7524  ,
        9715.841   ,  1131.5066  , 15828.82173 , 11842.62375 ,
        2020.5523  ,  5693.4305  ,  2904.088   ,  7448.40395 ,
        2597.779   ,  7337.748   , 23887.6627  , 38709.176   ,
        4687.797   ,  2643.2685  , 11674.13    , 12124.9924  ,
        4889.9995  , 12333.828   ,  3579.8287  ,  4391.652   ,
       42124.5153  ,  4463.2051  , 13887.204   ,  1719.4363  ,
       28476.73499 ,  1708.92575 , 10594.2257  , 25333.33284 ,
        3645.0894  , 38746.3551  , 11848.141   , 10564.8845  ,
       13880.949   ,  4753.6368  , 27941.28758 ,  8017.06115 ,
       23045.56616 ,  4133.64165 , 17942.106   , 25992.82104 ,
        3594.17085 ,  1682.597   ,  6079.6715  ,  9411.005   ,
        8283.6807  ,  6338.0756  ,  7152.6714  ,  4889.0368  ,
        4846.92015 , 11454.0215  ,  4349.462   ,  9101.798   ,
        1391.5287  , 28101.33305 ,  5152.134   , 38511.6283  ,
       44501.3982  , 41097.16175 ,  4837.5823  , 10601.63225 ,
        8310.83915 , 11264.541   , 15230.32405 , 27037.9141  ,
       23401.30575 ,  5031.26955 , 38282.7495  ,  6875.961   ,
       19719.6947  ,  1880.07    , 18765.87545 ,  6402.29135 ,
        4527.18295 ,  1743.214   ,  5709.1644  , 12363.547   ,
       13129.60345 ,  1727.54    ,  7731.4271  , 21195.818   ,
        1702.4553  , 23244.7902  , 23082.95533 ,  2927.0647  ,
       13019.16105 , 37701.8768  ,  9778.3472  ,  1980.07    ,
       30259.99556 , 22478.6     ,  6313.759   ,  2789.0574  ,
        5594.8455  ,  7261.741   , 11396.9002  ,  1986.9334  ,
        4719.73655 ,  7749.1564  ,  7345.7266  ,  9288.0267  ,
       12244.531   ,  1837.2819  ,  3972.9247  ,  5934.3798  ,
        5836.5204  ,  7935.29115 ,  5649.715   , 12347.172   ,
       12404.8791  , 22144.032   , 42983.4585  , 37270.1512  ,
        5267.81815 ,  9866.30485 ,  2322.6218  , 33471.97189 ,
        2137.6536  , 23306.547   ,  5261.46945 ,  3761.292   ,
       11436.73815 ,  4751.07    , 46661.4424  ,  2690.1138  ,
        1146.7966  , 37607.5277  ,  6373.55735 ,  4518.82625 ,
       13555.0049  ,  8547.6913  , 34439.8559  , 39125.33225 ,
       13607.36875 ,  2710.82855 , 14988.432   ,  2396.0959  ,
        3591.48    ,  7162.0122  , 48824.45    , 43578.9394  ,
       39556.4945  ,  2632.992   ,  9182.17    ,  6238.298   ,
        5757.41345 ,  4239.89265 ,  2154.361   , 21978.6769  ,
       16297.846   , 13831.1152  , 32734.1863  , 11830.6072  ,
       29523.1656  ,  3167.45585 ,  8428.0693  ,  5012.471   ,
        5209.57885 ,  2855.43755 , 20277.80751 ,  3554.203   ,
        8569.8618  , 10594.50155 ,  3597.596   ,  7323.734819,
        2731.9122  , 38711.      , 12981.3457  ,  9283.562   ,
        2709.1119  , 12096.6512  ,  2198.18985 ,  8932.084   ,
        3176.2877  , 24393.6224  ,  4266.1658  , 22493.65964 ,
       17085.2676  , 16577.7795  ,  8827.2099  ,  4296.2712  ,
        7804.1605  ,  3208.787   , 12957.118   , 22192.43711 ,
        9432.9253  , 17043.3414  ,  6593.5083  ,  4137.5227  ,
        4779.6023  , 14001.2867  , 12629.8967  ,  5245.2269  ,
        2404.7338  ,  6948.7008  ,  6435.6237  , 42560.4304  ,
        2055.3249  , 34672.1472  ,  1731.677   ,  1639.5631  ,
        9377.9047  , 10977.2063  ,  1534.3045  ,  9644.2525  ,
        4529.477   , 37829.7242  ,  9991.03765 ,  8125.7845  ,
        3877.30425 ,  5979.731   , 43896.3763  ,  1674.6323  ,
       13204.28565 , 44585.45587 ,  3021.80915 ,  3392.9768  ,
        1632.03625 ,  2699.56835 , 20177.67113 ,  4076.497   ,
       12592.5345  ,  1621.3402  ,  1875.344   ,  7196.867   ,
        3161.454   , 12029.2867  ,  2719.27975 , 18218.16139 ,
       12146.971   ,  3292.52985 ,  8688.85885 ,  6113.23105 ,
        8059.6791  , 13415.0381  , 18246.4955  , 47055.5321  ,
       12222.8983  ,  6067.12675 , 63770.42801 ,  9872.701   ,
        9193.8385  ,  8534.6718  , 27117.99378 ,  8596.8278  ,
       12475.3513  , 13405.3903  ,  2150.469   , 13747.87235 ,
        6610.1097  , 39047.285   , 27375.90478 ,  9048.0273  ,
        8988.15875 , 14901.5167  , 10096.97    ,  8835.26495 ,
       38415.474   ,  2721.3208  ,  9877.6077  , 47269.854   ,
        4237.12655 ,  2534.39375 ,  2205.9808  , 10965.446   ,
       15006.57945 , 10736.87075 ,  9788.8659  , 10422.91665 ,
        9304.7019  ,  3378.91    ,  2155.6815  , 38126.2465  ,
       35491.64    ,  6356.2707  , 24059.68019 , 16450.8947  ,
       12925.886   , 36950.2567  ,  2459.7201  , 46889.2612  ,
        5124.1887  , 14133.03775 ,  6414.178   ,  1720.3537  ,
       15817.9857  , 13462.52    ,  2103.08    , 12105.32    ,
       20781.48892 , 12235.8392  , 41949.2441  , 12643.3778  ,
       21223.6758  ,  7954.517   , 15170.069   ,  3659.346   ,
        8232.6388  ,  8027.968   , 13919.8229  , 10791.96    ,
       17878.90068 , 10601.412   , 13217.0945  , 11944.59435 ,
       14358.36437 , 32548.3405  ,  5699.8375  ,  2352.96845 ,
        4340.4409  ,  9391.346   , 42211.1382  ,  8823.279   ,
       14256.1928  ,  7133.9025  ,  5312.16985 ,  3906.127   ,
        2203.47185 , 28340.18885 ,  5484.4673  ,  1622.1885  ,
       11299.343   ,  8026.6666  , 11737.84884 ,  2913.569   ,
        9861.025   ,  2473.3341  , 39983.42595 , 36307.7983  ,
       44400.4064  ,  3172.018   ,  7742.1098  ,  6185.3208  ,
        1880.487   , 21771.3423  ,  6858.4796  , 17179.522   ,
       42760.5022  ,  5478.0368  , 12638.195   ,  5989.52365 ,
        9566.9909  , 10370.91255 , 19594.80965 , 11576.13    ,
        6360.9936  ,  4032.2407  ,  2585.269   , 11658.37915 ,
       21082.16    , 10807.4863  ,  9724.53    ,  3201.24515 ,
        3309.7926  ,  5969.723   ,  8269.044   ,  9414.92    ,
       23967.38305 , 47928.03    , 11842.442   ,  7421.19455 ,
       12950.0712  , 11033.6617  ,  6082.405   ,  3989.841   ,
        7537.1639  ,  3484.331   ,  8116.68    , 17626.23951 ,
       11837.16    ,  9541.69555 ,  4399.731   ,  2200.83085 ,
       11363.2832  ,  1964.78    , 13429.0354  , 24603.04837 ,
       27322.73386 , 42303.69215 , 42112.2356  , 41676.0811  ,
        4562.8421  ,  3490.5491  , 12485.8009  ,  6748.5912  ,
       45863.205   ,  2166.732   ,  6457.8434  , 12094.478   ,
       19515.5416  ,  4915.05985 ,  2523.1695  , 11566.30055 ,
       23241.47453 ,  4074.4537  ,  6600.20595 ,  1242.816   ,
       19361.9988  ,  8603.8234  ,  5972.378   ,  3171.6149  ,
        5375.038   , 12629.1656  , 19040.876   ,  8219.2039  ,
        7348.142   ,  4347.02335 ,  6753.038   ,  2457.502   ,
        5976.8311  , 18806.14547 , 11070.535   , 10065.413   ,
       24671.66334 ,  1824.2854  ,  7325.0482  , 40103.89    ,
       39725.51805 ,  1748.774   , 48173.361   , 35585.576   ,
       35160.13457 ,  1263.249   , 12982.8747  ,  1261.442   ,
        8444.474   , 36124.5737  , 15161.5344  , 10600.5483  ,
        6393.60345 , 12129.61415 , 22395.74424 ,  8733.22925 ,
       21984.47061 , 11881.358   ,  9910.35985 ,  7228.21565 ,
        2438.0552  ,  4357.04365 ,  8410.04685 ,  5488.262   ,
       21659.9301  , 12269.68865 ,  1769.53165 , 39597.4072  ,
       34838.873   ,  2897.3235  ,  1149.3959  , 19023.26    ,
        4667.60765 , 11945.1327  , 12479.70895 ,  3756.6216  ,
        6186.127   ,  8968.33    ,  1917.3184  ,  1977.815   ,
        4466.6214  ,  2136.88225 ,  2727.3951  , 24915.22085 ,
       12797.20962 , 40182.246   , 33907.548   , 12574.049   ,
       24227.33724 ,  4433.3877  , 10579.711   ,  7160.094   ,
       11187.6567  , 14235.072   , 10072.05505 ,  6389.37785 ,
        9875.6804  ,  8162.71625 ,  1826.843   , 10085.846   ,
        4571.41305 ,  9249.4952  , 31620.00106 ,  1708.0014  ,
        9487.6442  , 18223.4512  , 12523.6048  , 48970.2476  ,
       40419.0191  ,  8342.90875 ,  5116.5004  , 36021.0112  ,
        1241.565   , 38792.6856  ,  9617.66245 ,  3206.49135 ,
       13844.506   ,  4449.462   ,  8240.5896  ,  1737.376   ,
       17128.42608 ,  5425.02335 ,  7371.772   ,  3213.62205 ,
       12268.63225 , 17929.30337 , 21677.28345 , 13635.6379  ,
        5966.8874  ,  5257.50795 , 10156.7832  , 43921.1837  ])

In [34]:
for i in range(len(predict)):
    print(f" {y[i]} :  {predict[i]}")

 9095.06825 :  8528.588969240729
 5272.1758 :  4912.668037520023
 29330.98315 :  29743.359196251768
 9301.89355 :  9437.502222728606
 33750.2918 :  28028.485993032355
 4536.259 :  4800.730563923664
 2117.33885 :  1706.5537239944551
 14210.53595 :  14273.631896428644
 3732.6251 :  3343.6431578793363
 10264.4421 :  10494.810677028801
 18259.216 :  19291.08036488926
 7256.7231 :  7341.296922301639
 3947.4131 :  3952.0672409143026
 46151.1245 :  41304.61357421289
 48673.5588 :  43206.58608490904
 44202.6536 :  46257.42781814272
 9800.8882 :  9883.033362580023
 42969.8527 :  45060.07039682064
 8233.0975 :  8245.020102154289
 21774.32215 :  25938.594114463885
 5080.096 :  6012.0008741463025
 7441.501 :  7946.561897705575
 1256.299 :  1864.2784184831726
 2755.02095 :  2316.966123903474
 11085.5868 :  10832.99555811597
 10923.9332 :  10411.844002903916
 12644.589 :  12744.127669271991
 18804.7524 :  4713.890561807402
 9715.841 :  9158.680732443232
 1131.5066 :  1736.3390880457264
 15828.82173 :  8254.003817165245
 11842.62375 :  11551.096144863517
 2020.5523 :  2179.9752606919865
 5693.4305 :  5578.339795929494
 2904.088 :  3407.306783595295
 7448.40395 :  7356.271031951981
 2597.779 :  2530.430030922469
 7337.748 :  7325.938745095149
 23887.6627 :  24829.298736804398
 38709.176 :  40847.51686881047
 4687.797 :  4966.683692161778
 2643.2685 :  2786.793454593708
 11674.13 :  11987.633692158455
 12124.9924 :  12311.645331223106
 4889.9995 :  5386.275213986397
 12333.828 :  13030.987116024604
 3579.8287 :  3467.408569643185
 4391.652 :  4358.56592528826
 42124.5153 :  38682.01457000938
 4463.2051 :  4998.563933450865
 13887.204 :  13921.715079363892
 1719.4363 :  2199.750362825569
 28476.73499 :  6334.1623114081085
 1708.92575 :  1631.5351556254373
 10594.2257 :  11180.526378310558
 25333.33284 :  10296.731283735136
 3645.0894 :  3564.374269588643
 38746.3551 :  33078.32561267208
 11848.141 :  11950.207966556329
 10564.8845 :  10046.318186825993
 13880.949 :  13944.75685032958
 4753.6368 :  4877.986971929018
 27941.28758 :  15222.415431302532
 8017.06115 :  7644.148422807724
 23045.56616 :  9665.50487314382
 4133.64165 :  3727.930268891594
 17942.106 :  16240.122365298397
 25992.82104 :  11490.722570252112
 3594.17085 :  3163.157325686074
 1682.597 :  2316.001597615179
 6079.6715 :  5891.511628311297
 9411.005 :  8899.77579064389
 8283.6807 :  8302.784173371469
 6338.0756 :  6801.703349586524
 7152.6714 :  7598.66682653282
 4889.0368 :  4911.959955851546
 4846.92015 :  4779.325638302867
 11454.0215 :  11147.217982234664
 4349.462 :  4425.6526817556605
 9101.798 :  9118.931902585575
 1391.5287 :  2038.9215410913148
 28101.33305 :  29150.82686795303
 5152.134 :  5143.365907956702
 38511.6283 :  36294.002986380474
 44501.3982 :  28251.610776944246
 41097.16175 :  35582.41351256407
 4837.5823 :  5266.897650939964
 10601.63225 :  10788.664803945165
 8310.83915 :  7927.847121983067
 11264.541 :  12104.897666277355
 15230.32405 :  15134.005744263006
 27037.9141 :  24386.19004377239
 23401.30575 :  27259.512264524546
 5031.26955 :  4931.502144862281
 38282.7495 :  40562.092783819025
 6875.961 :  7352.722435018737
 19719.6947 :  29122.32017003894
 1880.07 :  2035.229690439559
 18765.87545 :  18363.531068935874
 6402.29135 :  5877.934541786484
 4527.18295 :  4140.4900701735405
 1743.214 :  1828.6336176825807
 5709.1644 :  6178.65994312713
 12363.547 :  13268.793012213366
 13129.60345 :  13087.745508036956
 1727.54 :  2338.2439077376057
 7731.4271 :  8234.672720311883
 21195.818 :  19086.261692906042
 1702.4553 :  1592.0962990514
 23244.7902 :  23035.308103018433
 23082.95533 :  1911.9169470254747
 2927.0647 :  3422.915903401872
 13019.16105 :  12769.811942120343
 37701.8768 :  35185.536635420896
 9778.3472 :  9271.663323332896
 1980.07 :  2538.9812775571645
 30259.99556 :  12720.424252046445
 22478.6 :  27574.17095764632
 6313.759 :  6280.073560604791
 2789.0574 :  2863.0694698241186
 5594.8455 :  4980.402039589713
 7261.741 :  7366.566823981299
 11396.9002 :  11103.147793835597
 1986.9334 :  2605.271420159692
 4719.73655 :  4383.733167318347
 7749.1564 :  7359.076959668592
 7345.7266 :  7318.734759590622
 9288.0267 :  9261.11517135325
 12244.531 :  12349.114325222748
 1837.2819 :  2463.5127304827693
 3972.9247 :  4018.3610698878747
 5934.3798 :  6376.92414332879
 5836.5204 :  5823.950951400331
 7935.29115 :  7362.8899837137815
 5649.715 :  5662.14886895535
 12347.172 :  13208.204608489192
 12404.8791 :  4251.246372523021
 22144.032 :  31254.463591214735
 42983.4585 :  42479.42825514211
 37270.1512 :  31600.65943913995
 5267.81815 :  4888.5038894153295
 9866.30485 :  9331.856880372512
 2322.6218 :  2924.0098640003653
 33471.97189 :  11113.07070591838
 2137.6536 :  2646.1557419633336
 23306.547 :  27075.17742463469
 5261.46945 :  5351.201927504233
 3761.292 :  3815.246312266723
 11436.73815 :  11353.982281843342
 4751.07 :  5220.932440549837
 46661.4424 :  41608.077972424086
 2690.1138 :  2373.9255957657606
 1146.7966 :  1898.1622941858059
 37607.5277 :  37360.32710594699
 6373.55735 :  5814.564692592836
 4518.82625 :  4470.732102640921
 13555.0049 :  13542.250624447448
 8547.6913 :  8577.627734106683
 34439.8559 :  29566.661621375795
 39125.33225 :  38281.43671875131
 13607.36875 :  13430.177384411189
 2710.82855 :  2225.734180895026
 14988.432 :  15427.392018627135
 2396.0959 :  2297.603680535125
 3591.48 :  4244.146390072563
 7162.0122 :  7668.5450520114455
 48824.45 :  42257.83227841867
 43578.9394 :  35349.0430738376
 39556.4945 :  36667.729060103884
 2632.992 :  2733.742738788096
 9182.17 :  9252.373064719388
 6238.298 :  6203.660594490562
 5757.41345 :  5621.1567880688435
 4239.89265 :  4331.951632354394
 2154.361 :  2198.6491609511468
 21978.6769 :  25932.1286124669
 16297.846 :  21872.939917863157
 13831.1152 :  14155.185269120007
 32734.1863 :  13074.360610853822
 11830.6072 :  11534.919428015959
 29523.1656 :  30855.700369826493
 3167.45585 :  2837.5084397197315
 8428.0693 :  8651.780360810677
 5012.471 :  4976.150583294646
 5209.57885 :  5151.7893721217715
 2855.43755 :  2604.0996432501324
 20277.80751 :  3952.3794180254245
 3554.203 :  3596.6890825851133
 8569.8618 :  8366.456961590273
 10594.50155 :  10764.509196713641
 3597.596 :  4463.54192774691
 7323.734819 :  1711.9322488524285
 2731.9122 :  2127.965740670259
 38711.0 :  39429.965741002015
 12981.3457 :  13468.465885845366
 9283.562 :  9333.271311061308
 2709.1119 :  2202.2500082287534
 12096.6512 :  11705.466503338632
 2198.18985 :  1636.2446949400382
 8932.084 :  8959.50715476593
 3176.2877 :  2783.664070159497
 24393.6224 :  28448.78164491833
 4266.1658 :  4912.276855797269
 22493.65964 :  2999.882990257054
 17085.2676 :  22023.359626386602
 16577.7795 :  19227.784081452217
 8827.2099 :  8954.958574236885
 4296.2712 :  4078.682167209863
 7804.1605 :  8313.289528084477
 3208.787 :  3200.4933328152874
 12957.118 :  13441.470882167167
 22192.43711 :  12126.748114142803
 9432.9253 :  8779.806893943618
 17043.3414 :  22687.505070756284
 6593.5083 :  7090.677525066293
 4137.5227 :  3600.0929753134897
 4779.6023 :  4768.820758513311
 14001.2867 :  14161.418964420724
 12629.8967 :  12701.436093089476
 5245.2269 :  5198.374011405136
 2404.7338 :  2182.77109605031
 6948.7008 :  7052.857247712461
 6435.6237 :  7247.829181401787
 42560.4304 :  44876.90380185548
 2055.3249 :  2296.3640621446084
 34672.1472 :  30761.92828601593
 1731.677 :  1735.4432744081914
 1639.5631 :  1868.3870202802464
 9377.9047 :  9977.989621893332
 10977.2063 :  10779.684937225325
 1534.3045 :  2184.683925598536
 9644.2525 :  9432.503995232039
 4529.477 :  4558.905819959489
 37829.7242 :  27550.531254438698
 9991.03765 :  9766.354179895414
 8125.7845 :  8657.04808346472
 3877.30425 :  4063.984961192413
 5979.731 :  6473.226452241341
 43896.3763 :  45560.26965529006
 1674.6323 :  2310.894376694041
 13204.28565 :  12625.85056474141
 44585.45587 :  37777.014135499085
 3021.80915 :  2763.535796458138
 3392.9768 :  3406.447243122717
 1632.03625 :  1735.732620110628
 2699.56835 :  2910.5109979650897
 20177.67113 :  4355.874946478254
 4076.497 :  4557.377532988476
 12592.5345 :  11169.43747322531
 1621.3402 :  1931.8142101056928
 1875.344 :  1975.7270528167537
 7196.867 :  7690.2299484748455
 3161.454 :  3181.889864063187
 12029.2867 :  11536.250274222053
 2719.27975 :  2391.562997317911
 18218.16139 :  3256.9991063751004
 12146.971 :  12721.929655557306
 3292.52985 :  3421.2490902700647
 8688.85885 :  8653.749636435181
 6113.23105 :  5439.826929623476
 8059.6791 :  7615.660331184288
 13415.0381 :  13053.098645293965
 18246.4955 :  26399.721725246345
 47055.5321 :  40394.68705315073
 12222.8983 :  11922.18933303004
 6067.12675 :  5951.552122632334
 63770.42801 :  39157.63564091561
 9872.701 :  10029.881267708923
 9193.8385 :  8982.743778984157
 8534.6718 :  7969.369242880537
 27117.99378 :  9668.444649199075
 8596.8278 :  8283.261271998388
 12475.3513 :  12019.58504900823
 13405.3903 :  13719.924287778866
 2150.469 :  2140.420488619404
 13747.87235 :  13402.013755504486
 6610.1097 :  6338.7900821527965
 39047.285 :  39753.63542421918
 27375.90478 :  5691.422116964486
 9048.0273 :  9658.927713659505
 8988.15875 :  8614.191269305506
 14901.5167 :  14216.499157553091
 10096.97 :  10901.870895141192
 8835.26495 :  8969.389416626473
 38415.474 :  37532.204916502975
 2721.3208 :  2655.630788642453
 9877.6077 :  10021.528903856495
 47269.854 :  47229.65813856399
 4237.12655 :  4135.304778574218
 2534.39375 :  2761.065361470086
 2205.9808 :  1774.6009028604421
 10965.446 :  11533.237810520004
 15006.57945 :  12463.66957851618
 10736.87075 :  10722.983714764232
 9788.8659 :  10642.9947319109
 10422.91665 :  10402.906544510173
 9304.7019 :  9991.221558630565
 3378.91 :  3426.5197218607154
 2155.6815 :  2221.159470238237
 38126.2465 :  36946.03818529388
 35491.64 :  30952.839873906072
 6356.2707 :  6825.043162533424
 24059.68019 :  3131.33808143667
 16450.8947 :  20458.430697011725
 12925.886 :  13735.484852856538
 36950.2567 :  36500.4467964572
 2459.7201 :  1996.9193494014635
 46889.2612 :  39148.351212972484
 5124.1887 :  5617.308172718067
 14133.03775 :  1850.275082795526
 6414.178 :  6303.694989477895
 1720.3537 :  2220.3262640624325
 15817.9857 :  17908.963763896892
 13462.52 :  13544.288999227509
 2103.08 :  2493.160432963863
 12105.32 :  12406.70998454569
 20781.48892 :  10790.296809170914
 12235.8392 :  11954.380340504638
 41949.2441 :  38775.7186821892
 12643.3778 :  12674.94206966248
 21223.6758 :  22815.153588412366
 7954.517 :  7946.394415550802
 15170.069 :  15734.207789803724
 3659.346 :  4151.85495743062
 8232.6388 :  8243.891483416084
 8027.968 :  8529.000752269363
 13919.8229 :  14831.791025627575
 10791.96 :  11331.397512598767
 17878.90068 :  2739.150031217918
 10601.412 :  11155.369048319391
 13217.0945 :  12715.536646650724
 11944.59435 :  11956.701163704725
 14358.36437 :  4983.989708735999
 32548.3405 :  25677.783972961573
 5699.8375 :  6194.1866503280635
 2352.96845 :  2447.042480732087
 4340.4409 :  4352.863945916912
 9391.346 :  9980.961034342126
 42211.1382 :  44475.47960098478
 8823.279 :  8851.659669182378
 14256.1928 :  13907.48580863737
 7133.9025 :  6807.287293191281
 5312.16985 :  4836.063939627467
 3906.127 :  4333.158711040764
 2203.47185 :  1735.739426088403
 28340.18885 :  7928.366049471235
 5484.4673 :  5951.374956456695
 1622.1885 :  1763.3592266562973
 11299.343 :  11488.388188143317
 8026.6666 :  7633.75290490798
 11737.84884 :  5574.767744681243
 2913.569 :  2955.6310530316678
 9861.025 :  9925.806232813597
 2473.3341 :  2606.301747872034
 39983.42595 :  34206.03783796738
 36307.7983 :  33543.02763389331
 44400.4064 :  42712.57874065687
 3172.018 :  3273.80514911478
 7742.1098 :  8241.91975729959
 6185.3208 :  6182.55348894835
 1880.487 :  2038.600811019236
 21771.3423 :  24780.50093348402
 6858.4796 :  6773.922833616347
 17179.522 :  15812.588951568829
 42760.5022 :  44035.980205608495
 5478.0368 :  5456.910566021443
 12638.195 :  12730.33995841492
 5989.52365 :  5602.810672436955
 9566.9909 :  9237.167743046366
 10370.91255 :  9958.067773731593
 19594.80965 :  17163.878999875724
 11576.13 :  12053.007857717654
 6360.9936 :  6202.8680026320635
 4032.2407 :  4122.581071279243
 2585.269 :  2767.8196452813336
 11658.37915 :  11148.087381195863
 21082.16 :  29665.664075502857
 10807.4863 :  11555.28704279975
 9724.53 :  10350.294124560209
 3201.24515 :  2893.892906919873
 3309.7926 :  3174.209019560687
 5969.723 :  6443.419109661034
 8269.044 :  8315.936901937546
 9414.92 :  9505.38911516801
 23967.38305 :  26165.249263834077
 47928.03 :  42865.98091240071
 11842.442 :  11927.751738662659
 7421.19455 :  7022.969233840024
 12950.0712 :  13094.425158128477
 11033.6617 :  10471.719477555223
 6082.405 :  6550.830198413992
 3989.841 :  3988.4067076647825
 7537.1639 :  7074.20778882309
 3484.331 :  4021.5484602428314
 8116.68 :  8615.924426123827
 17626.23951 :  4551.721111674266
 11837.16 :  11919.719536667335
 9541.69555 :  8903.89564096952
 4399.731 :  4910.365445710511
 2200.83085 :  1686.6809362887707
 11363.2832 :  11955.965033581264
 1964.78 :  2345.2171176733646
 13429.0354 :  13135.443365328749
 24603.04837 :  7633.7898790564395
 27322.73386 :  12443.723185236928
 42303.69215 :  34402.96339915457
 42112.2356 :  37321.476596763685
 41676.0811 :  40922.94614064479
 4562.8421 :  4557.060542874764
 3490.5491 :  3423.19334538729
 12485.8009 :  12701.469555477204
 6748.5912 :  6549.202230006222
 45863.205 :  39773.12151857977
 2166.732 :  2316.6598275658453
 6457.8434 :  6527.666085839316
 12094.478 :  12066.875934958964
 19515.5416 :  21947.168943562574
 4915.05985 :  4963.465797969371
 2523.1695 :  2683.1495089149666
 11566.30055 :  11495.435785950736
 23241.47453 :  3830.677688432872
 4074.4537 :  4557.907865198173
 6600.20595 :  6463.643086944124
 1242.816 :  1732.5031317785779
 19361.9988 :  20579.12908375567
 8603.8234 :  8554.29345834069
 5972.378 :  6040.207114279381
 3171.6149 :  3273.386038487599
 5375.038 :  5372.56132646838
 12629.1656 :  12721.486173252928
 19040.876 :  25925.064676988302
 8219.2039 :  8225.772970971517
 7348.142 :  7359.922567803998
 4347.02335 :  3834.729120624548
 6753.038 :  6544.227031799662
 2457.502 :  2440.9558023631816
 5976.8311 :  5949.5598959415165
 18806.14547 :  7967.927222176779
 11070.535 :  11148.040596700472
 10065.413 :  10615.57788318379
 24671.66334 :  5007.67094230675
 1824.2854 :  2447.0848376361555
 7325.0482 :  6734.42840399277
 40103.89 :  41098.1560051324
 39725.51805 :  35278.21761794798
 1748.774 :  1909.2036569402935
 48173.361 :  43200.406263485376
 35585.576 :  33561.34481600662
 35160.13457 :  11424.159010595413
 1263.249 :  1935.0221635870894
 12982.8747 :  13426.058151573507
 1261.442 :  1923.6501114329349
 8444.474 :  8954.15426907206
 36124.5737 :  33399.89236011892
 15161.5344 :  16014.044369561734
 10600.5483 :  10913.940226039256
 6393.60345 :  6475.701651649912
 12129.61415 :  12322.522205091933
 22395.74424 :  3514.129613810519
 8733.22925 :  8914.230647654644
 21984.47061 :  4184.873956794861
 11881.358 :  12127.462331908417
 9910.35985 :  9617.62918042456
 7228.21565 :  6718.613614926401
 2438.0552 :  3475.698108633096
 4357.04365 :  4027.019374089785
 8410.04685 :  8521.809457185715
 5488.262 :  5948.9855634116575
 21659.9301 :  22271.887625291845
 12269.68865 :  12262.707020028076
 1769.53165 :  1978.7752499661856
 39597.4072 :  31724.86826913784
 34838.873 :  30027.398841328366
 2897.3235 :  2888.1383443903687
 1149.3959 :  1960.9709555814097
 19023.26 :  14158.052771816658
 4667.60765 :  4485.935082227139
 11945.1327 :  12380.34177252238
 12479.70895 :  12129.956636621657
 3756.6216 :  3770.879583396845
 6186.127 :  6185.585792312382
 8968.33 :  9542.585242682671
 1917.3184 :  2184.695871216876
 1977.815 :  2555.1441619478155
 4466.6214 :  4353.15798043209
 2136.88225 :  1942.8913595196518
 2727.3951 :  2737.89943137676
 24915.22085 :  29483.180638833837
 12797.20962 :  7059.857073259317
 40182.246 :  28713.753768251863
 33907.548 :  26906.472250832754
 12574.049 :  12851.436933191879
 24227.33724 :  11831.548532876339
 4433.3877 :  4582.725201244837
 10579.711 :  10740.123561860086
 7160.094 :  7666.808560010694
 11187.6567 :  11035.014047158722
 14235.072 :  14675.423986871112
 10072.05505 :  10026.720409342002
 6389.37785 :  6480.204248204386
 9875.6804 :  9327.17354139056
 8162.71625 :  8232.732459129198
 1826.843 :  2457.0364265224034
 10085.846 :  10796.163831126458
 4571.41305 :  4205.177524016644
 9249.4952 :  8908.415423250195
 31620.00106 :  14462.902419716624
 1708.0014 :  1616.0398823666092
 9487.6442 :  10022.054199590048
 18223.4512 :  19817.097178926728
 12523.6048 :  12700.246044853266
 48970.2476 :  47613.8778917748
 40419.0191 :  40849.096883708284
 8342.90875 :  8221.534639282636
 5116.5004 :  5463.217654041768
 36021.0112 :  31816.119310361406
 1241.565 :  1765.6346963999476
 38792.6856 :  33943.91225224434
 9617.66245 :  9586.45468772766
 3206.49135 :  2612.76357727693
 13844.506 :  13706.084487599685
 4449.462 :  4952.271175644193
 8240.5896 :  8272.71809762361
 1737.376 :  1726.5897956937206
 17128.42608 :  4776.684635090804
 5425.02335 :  5450.074979992649
 7371.772 :  7374.916888915363
 3213.62205 :  2704.2336797437
 12268.63225 :  12241.636012306928
 17929.30337 :  7340.089101610722
 21677.28345 :  22621.426155866036
 13635.6379 :  13135.597651094598
 5966.8874 :  6447.9621913735045
 5257.50795 :  5388.022982400531
 10156.7832 :  9819.7602512999
 43921.1837 :  38730.450165528506

In [35]:
from sklearn.metrics import r2_score

r2_score(y_test, predict)

0.8346048765714105

In [36]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'C': [0.1, 1, 10, 100, 1000, 10000, 100000],
    'gamma': [0.001,0.01, 0.1, 1, 10]
}

# Create SVR model
svr = SVR(kernel='rbf')

# Create GridSearchCV object
grid_search = GridSearchCV(estimator=svr, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

# Fit the grid search to the data
grid_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Get the best model
best_svr = grid_search.best_estimator_

# Predictions
y_pred_train_best = best_svr.predict(X_train)
y_pred_test_best = best_svr.predict(X_test)

# Evaluating the model
# train_rmse_best = np.sqrt(mean_squared_error(y_train, y_pred_train_best))
# test_rmse_best = np.sqrt(mean_squared_error(y_test, y_pred_test_best))
# print("Train RMSE (Best Model):", train_rmse_best)
# print("Test RMSE (Best Model):", test_rmse_best)

Best Hyperparameters: {'C': 100000, 'gamma': 0.1}

In [37]:
y_pred_test_best

array([ 8554.99805984,  4877.20999461, 31538.82045697,  9356.53636341,
       28363.96846372,  4941.7870046 ,  1760.9270708 , 14319.93857318,
        3378.56956606, 10359.93442739, 18613.53347824,  7336.75870231,
        3929.92845806, 46457.96702254, 49171.31453414, 47556.08990112,
        9517.18016658, 44964.79721825,  8242.34353415, 23979.84982132,
        5307.77426462,  7915.20308094,  1751.77183447,  2170.75114858,
       10701.94161552, 10410.40353878, 12737.55679368,  4856.09383907,
        9151.9897855 ,  1620.80093952,  8139.68817284, 11549.71385353,
        2020.33730187,  5520.79179768,  3358.26896263,  7340.11919442,
        2446.64822435,  7344.28144023, 23557.97594084, 39190.51184289,
        4654.14081894,  2697.2370225 , 11702.61604727, 12335.08894284,
        5360.55331713, 12958.35277729,  3412.34214154,  4497.38137411,
       42545.78039453,  4892.33153657, 13939.32920142,  2064.56778537,
        6426.63298637,  1614.56977452, 11170.92084884, 10202.7716408 ,
        3623.18919644, 35965.68274073, 11946.82760916, 10044.38771993,
       13953.81425993,  4472.9392544 , 15238.65017049,  7698.29297373,
        9661.1149628 ,  3735.79994088, 15979.44650753, 11383.60912494,
        3165.91802232,  2170.68906041,  5985.44252049,  8843.53669879,
        8302.45305191,  6797.59677168,  7598.35935936,  4877.06212417,
        4904.28530293, 11132.11051501,  4410.59326864,  9047.44402684,
        1882.47226425, 30525.58068827,  5168.46766359, 37363.52305366,
       27648.49078656, 36601.67860524,  5352.94169397, 10786.52589755,
        7910.59703134, 12001.56660659, 14626.97074795, 26039.91414659,
       24477.21190853,  4986.18722112, 39203.11722805,  7338.77328816,
       24919.70840808,  1882.77571259, 17750.33487901,  5996.02059141,
        4131.283715  ,  1753.84669624,  6188.85765758, 13180.36668583,
       13183.34581484,  2211.1202661 ,  8210.50312964, 20186.36614379,
        1606.44228361, 22553.78982627,  1750.25929862,  3129.61477794,
       12586.97536307, 31841.80446037,  9250.54230943,  2433.03999125,
       12729.61216546, 25481.3432768 ,  6290.46488158,  2801.41157775,
        5021.06052559,  7338.27825875, 10756.45196203,  2476.08739319,
        4476.83028918,  7339.73582914,  7351.08592948,  9242.51886676,
       12338.44595241,  2317.7358132 ,  3990.9117937 ,  6404.11167744,
        5803.01182111,  7352.0121757 ,  5637.04099645, 12778.25420004,
        4202.04412968, 29992.8359672 , 46389.54453869, 30249.68972045,
        4880.65310223,  9329.48313243,  2813.79175604, 10803.19588335,
        2709.40340543, 26010.94829702,  5407.15353231,  3784.39695308,
       11253.98751601,  5238.328168  , 46602.18074954,  2353.02596283,
        1636.2442949 , 34876.50280443,  5936.07318412,  4424.63157921,
       13547.3864567 ,  8573.71532385, 30575.6213857 , 35627.09855374,
       13299.34223044,  2102.4098605 , 15495.65061812,  2388.25527862,
        4432.67248699,  7587.2737864 , 48410.8235436 , 37463.41655523,
       33915.74693447,  2661.4776416 ,  9215.6561817 ,  6248.36779417,
        5646.31703947,  4356.07718252,  2204.06333338, 23348.53349855,
       20726.09752476, 14236.30055075, 15902.38370837, 11543.05856677,
       32706.50533667,  2356.66381969,  8603.92202713,  5023.32468846,
        5226.37764833,  2478.96181851,  3930.12137813,  3597.19364507,
        8271.65173548, 10747.71889901,  4440.60354694,  1619.68259043,
        2236.61249934, 39634.3962343 , 13480.67200876,  9330.16368853,
        2070.42137222, 11643.03579268,  1614.98718229,  8904.39158962,
        2930.64663913, 27978.22248636,  4412.71502204,  3027.33074571,
       18992.216911  , 17473.26123735,  8908.48559022,  4022.18365154,
        8272.39050779,  3177.56171011, 13638.29295626, 12094.51250715,
        8577.78982382, 20613.08011064,  7160.25109893,  3594.94654122,
        4775.93215449, 14161.57322916, 12755.24108637,  5257.89075686,
        2020.81632627,  7044.33686301,  6888.49000395, 45763.2454436 ,
        2171.38987831, 29928.46390174,  1767.4558076 ,  1751.54428039,
        9939.97822793, 11124.53297648,  2022.39579897,  9265.41653379,
        4654.64696022, 25702.5691369 ,  9627.37396905,  8639.04306777,
        4072.04672212,  6464.41647767, 46796.45980097,  2166.48713086,
       12795.40684861, 37753.37656801,  2642.01976524,  3357.60148712,
        1758.21260748,  2827.42772513,  4411.19399077,  4564.18205978,
       11589.27830659,  1808.47140495,  1891.31568209,  7677.65795784,
        3240.80911241, 11550.9192678 ,  2271.60572791,  3202.96756591,
       12729.71863755,  3394.44659524,  8560.44216271,  5512.3604528 ,
        7558.3449284 , 13217.86107898, 24546.27995947, 45701.35311717,
       11923.5617262 ,  5969.55273283, 42550.59199793,  9928.67853009,
        9030.40259297,  7897.47654239,  9615.1768275 ,  8168.68338084,
       11970.85720348, 13783.39617807,  2227.1728481 , 14068.54571082,
        6430.57357588, 37601.58116835,  5817.4643212 ,  9503.2284677 ,
        8600.72295817, 14280.0894961 , 11288.11141919,  8968.69200846,
       36360.89147165,  2703.5438808 ,  9813.01225322, 48784.047278  ,
        4132.89117543,  2641.57442222,  1622.96265833, 11527.59547456,
       14754.57884378, 10759.92808403, 11017.79056209, 10362.18736477,
        9758.01601851,  3394.48843965,  2196.54778643, 41248.90904186,
       29500.01970509,  6559.02005687,  3145.90714968, 17691.27997392,
       13671.32500142, 38021.00856874,  1888.00006078, 44077.47751085,
        5399.25545973,  1639.01736449,  6327.29809112,  2086.26936164,
       16571.55040305, 13548.75355926,  2389.38787982, 12293.56299142,
       10787.6403023 , 11932.11089556, 43384.68398995, 12469.27512251,
       21736.20681973,  7888.51677488, 15746.87972848,  4141.89500989,
        8239.97966023,  8514.42113139, 14852.20596314, 11304.06079793,
        2647.65774962, 11096.88356301, 12731.2648316 , 11945.58284482,
        5018.54470083, 25218.36486658,  6180.23848818,  2564.72823819,
        4422.2392656 ,  9715.21520685, 44176.76991017,  8828.59298871,
       13979.80447051,  6908.04288241,  4970.91623389,  4514.53416216,
        1620.77311442,  7928.90586594,  5969.38909361,  1622.20324028,
       11465.86333604,  7597.58058155,  5636.44052663,  2888.41081721,
        9891.45735064,  2477.31212691, 36879.00352569, 37582.83251018,
       47150.38524812,  3179.05336551,  8234.31790652,  6160.03548744,
        1882.49529455, 21704.5240027 ,  6795.04314691, 16817.70546739,
       44638.36367267,  5475.12305048, 12733.45354475,  5554.55319924,
        9205.79642692,  9849.57224177, 17906.79342838, 11513.69356132,
        5926.96980504,  4169.37809751,  2356.09477914, 11139.98219925,
       25634.70586402, 11415.80931679, 10300.52406663,  2822.19939013,
        3154.5939088 ,  6407.81424589,  8224.84118645,  9381.3590364 ,
       25619.36840518, 45208.05750278, 11926.85894725,  6987.06795904,
       13088.86517706, 10799.37964705,  6536.91703464,  3999.70036604,
        7039.93829041,  4093.67971906,  8605.29037702,  4610.28192981,
       11930.81945235,  8817.81240553,  4876.78656092,  1618.42353273,
       11936.72044064,  2197.77974791, 13139.52006806,  7596.32112111,
       12331.93741184, 35837.42760226, 38892.46124851, 43967.69986047,
        4555.67049279,  3381.9809952 , 12611.34623712,  6548.00271305,
       43545.60491796,  2165.6835896 ,  6546.56722435, 12010.85000815,
       20170.30662163,  4736.85982406,  2688.06678497, 11434.08559739,
        3896.35535102,  4556.94472663,  6520.03660012,  1766.90417156,
       19942.34037734,  8602.27422398,  6010.85951014,  3179.70654697,
        5373.71845353, 12696.33571107, 21733.17299774,  8208.39140898,
        7356.87728814,  3774.64252646,  6464.38378206,  2577.27615902,
        5977.56874813,  7905.43355593, 11132.93147185, 10578.30620059,
        5090.95256023,  2322.60491437,  6685.6937774 , 40849.28799078,
       32401.43594755,  1750.21110521, 49198.56469182, 35719.66056591,
       11372.27477688,  1753.0140885 , 13444.37307609,  1750.96604429,
        8909.70877406, 32753.09500107, 16152.14568429, 10776.10373604,
        6496.7999173 , 12325.97932732,  3551.22709535,  8675.88325715,
        4263.76643631, 12051.38922217,  9589.16580668,  6774.4300364 ,
        2342.01888304,  3986.8456342 ,  8423.44321822,  5979.40550778,
       21778.37527078, 12077.70109092,  1890.83676109, 32846.22947662,
       29115.47651938,  2840.35410849,  1617.51272855, 11242.64988835,
        4580.23483819, 12168.14728742, 12057.1807576 ,  3816.16499432,
        6164.95336796,  9493.26555075,  2022.41306163,  2503.83030006,
        4463.49903843,  1755.68698128,  2659.23304025, 30199.12952674,
        7055.94345494, 33162.72871345, 26065.50875326, 12877.45240101,
       11779.79471735,  4585.53488653, 10397.77276727,  7609.31679824,
       10931.12931829, 14106.96247019, 10021.19825699,  6497.8870554 ,
        9262.17870485,  8135.34027394,  2317.73100131, 10582.63537441,
        4216.98655702,  8896.83037886, 13983.858154  ,  1613.0236568 ,
       10010.65799339, 20428.96912801, 12757.79570568, 49510.70442516,
       44078.36871012,  8148.71752292,  5435.69222096, 31177.03976268,
        1773.11105069, 39159.31017423,  9559.53800337,  2738.3587438 ,
       14221.3427096 ,  5058.58914911,  8272.54879001,  1758.58109919,
        5006.89299783,  5521.55183265,  7307.96035678,  2676.94974486,
       12085.40606042,  7331.70482181, 20716.59934768, 13132.66927242,
        6404.92211927,  5492.6499252 ,  9835.33301856, 42002.71722633])